# Generated by Django 5.0.6 on 2024-05-29 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chatroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Elobby",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "chatrooms",
                    models.ManyToManyField(
                        blank=True, related_name="elobbies", to="api.chatroom"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "username",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=100)),
                ("nickname", models.CharField(max_length=100)),
                (
                    "elobby",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profiles",
                        to="api.elobby",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "chatroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="api.chatroom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="api.userprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="elobby",
            name="usuarios",
            field=models.ManyToManyField(
                blank=True, related_name="elobbies", to="api.userprofile"
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_chatrooms",
                to="api.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="users",
            field=models.ManyToManyField(
                related_name="chatrooms", to="api.userprofile"
            ),
        ),
    ]
