# Generated by Django 5.0.6 on 2024-05-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="requests",
            field=models.ManyToManyField(
                related_name="chatroom_requests", to="api.userprofile"
            ),
        ),
    ]
